### PR TITLE
New Features

### PR DESCRIPTION
**Pull request by netcons**
Hi Andrea, could you have a look at the changes, perhaps help with translation of new features and Debian packaging. Thanks

### CODE REVIEW

**Comment by frisoft** [comment]
Hi @netcons, 

You did incredible work on Turtle Firewall.
I would be happy to merge back the changes into my repo.
However, you moved all the files and made it compatible only with CentOS, if I understand it well.

I want to keep the installation via wbm file as the standard way to install the module, so that it can be done on any distro.

Do you think you can change it on your side to make it wbm-first, and, then have a build script for packaging it for CentOS?

**Comment by frisoft** [comment]
Or, in alternative, I could merge your PR into a separate branch. Then, I can move the files around to make it wbm compatible.

**Comment by netcons** [comment]
Let me have a look at the WBM method again, I would prefer a distro independent install as well. 
Some thoughts:
Kernel module requirements will have to be handled separately, DKMS, RPM and APT ease this.
The file structure on Git is, as is on the OS and therefor in the RPM build root as well. which eases RPM build per commit.
File locations adhere to SystemD as on latest CentOS and Debian releases.
Perhaps a version 2 branch would make sense.

**Comment by frisoft** [comment]
Hi @netcons ,

I get that you are following CentOS file system structure, but webmin on Debian use a different structure and the WDM uses a very flat structure.
Also, not everyone uses systemd

Don't change your structure, for now.

I'll create a branch to merge your changes following your directory structure.

Then I can change the wbm build script to copy the files in the correct locations during build time.

Debian can wait, for now.

However, eventually, I would prefer a distro agnostic structure.

I'm on NixOS now, and would like to have it as a Nix package, eventually.

Thank you for all the amazing contributions.

**Comment by netcons** [comment]
Thanks, makes sense to keep the structure as it was, Applied accordingly.
Please note that rpm "pre" and "post" scripts handled old fw.xml config fixes, moved it to fixconfig.sh,
other functions handled by these scripts I added to setup.pl

Also, the GeoIP database download is handled with a separate script in a RPM for that kernel module,
located in /etc/cron.daily/xt_geoip_update, did not want to include it with TFW files.

```
#!/bin/bash
cd /var/tmp
/usr/libexec/xtables-addons/xt_geoip_dl
/usr/libexec/xtables-addons/xt_geoip_build -s
rm -rf dbip-country-lite.csv
```

**Comment by frisoft** [comment]
> Thanks, makes sense to keep the structure as it was, Applied accordingly.
> Please note that rpm "pre" and "post" scripts handled old fw.xml config fixes, moved it to fixconfig.sh,
> other functions handled by these scripts I added to setup.pl
> 
> Also, the GeoIP database download is handled with a separate script in a RPM for that kernel module,
> located in /etc/cron.daily/xt_geoip_update, did not want to include it with TFW files.
> 
> ```
> #!/bin/bash
> cd /var/tmp
> /usr/libexec/xtables-addons/xt_geoip_dl
> /usr/libexec/xtables-addons/xt_geoip_build -s
> rm -rf dbip-country-lite.csv
> ```

This is great. I opened a second pr, but now I think I'll come back to this one.

Thank you for this.

**Comment by frisoft** [comment]
@netcons, if you can, please, resolve the two conflicts, I'll be happy to merge the PR into my netcons branch.
Then, after some tests, I'll merge it into master.

**Comment by netcons** [comment]
All done.

**Comment by frisoft** [comment]
> All done.

Thank you very much.

**Pull request merged**
